# Generated by Django 5.2 on 2025-04-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('aadhaar', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('health_problem', models.TextField()),
                ('date_of_visit', models.CharField(max_length=10)),
            ],
        ),
    ]
