# Generated by Django 5.1.7 on 2025-04-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_demo', '0004_remove_article_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='state',
        ),
    ]
