# Generated by Django 5.2 on 2025-04-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='sname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='srollno',
            new_name='rollno',
        ),
    ]
